name: Publish post from issue

on:
  issues:
    types: ['labeled']

jobs:
  build:
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Post
        env:
          POST_TITLE: ${{ github.event.issue.title }}
          POST_BODY: ${{ github.event.issue.body }}
          POST_PATH: source/_posts/$POST_TITLE.md
        run: |
          mkdir -p source/_posts/
          touch $POST_PATH
          echo "---"                   >> $POST_PATH
          echo "title: $POST_TITLE"    >> $POST_PATH
          echo "date:"                 >> $POST_PATH
          echo "tags:"                 >> $POST_PATH
          echo "---"                   >> $POST_PATH
          echo ""                      >> $POST_PATH
          echo $POST_BODY              >> $POST_PATH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: "publish: ${{ github.event.issue.title}}"
          body: |
            Automagically sprouted for publishing.

            Merging will publish to: https://github.com/liuyib/hexo-blog-source/source/_posts/${{ github.event.issue.title }}.md

            Closes #${{ github.event.issue.number }}
          reviewers: "${{ github.repository_owner }}"
          commit-message: "post: ${{ github.event.issue.title }}"
