# Delete files that are used only in development.
name: "ShakeFiles"

on:
  push:
    branchs: [master]
  pull_request:
    branchs: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Move files
        run: |
          mkdir ./dist
          mv src ./dist/src
          mv LICENSE ./dist/LICENSE
          mv .gitignore ./dist/.gitignore

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          publish_branch: dist
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: Shake files that are used only in development
          disable_nojekyll: true
